name: DevSecOps Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  devsecops:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run SAST scan (CodeQL)
        uses: github/codeql-action/init@v2
        with:
          languages: javascript  # Specify relevant language
        - run: |
            npm audit
            npx eslint .  # For linting
        - run: npm test
        - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # Install SonarQube scanner
          npm install -g sonarqube-scanner
          
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=your_organization \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

      # --- Dependency Scanning (e.g., OWASP Dependency-Check) ---
      - name: OWASP Dependency Check
        run: |
   
          curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v7.1.1/dependency-check-7.1.1-release.zip
          unzip dependency-check-7.1.1-release.zip -d dependency-check
          
          ./dependency-check/bin/dependency-check.sh --project "your_project" --out reports/ --scan .

     
      - name: Snyk Dependency Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
       
          npm install -g snyk
        
          snyk auth $SNYK_TOKEN
        
          snyk test

     
      - name: Trivy Container Scan
        env:
          TRIVY_TOKEN: ${{ secrets.TRIVY_TOKEN }}
        run: |
       
          sudo apt-get install -y wget
          wget -qO- https://github.com/aquasecurity/trivy/releases/download/v0.29.2/trivy_0.29.2_Linux-64bit.tar.gz | tar zxvf - -C /usr/local/bin trivy
          
          trivy fs --exit-code 1 --severity HIGH,CRITICAL .

      # --- IaC Security (Checkov) ---
      - name: Checkov IaC Security Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
